export const firestoreCollections = {
  categories: 'categories',
  products: 'products',
  productVariants: 'productVariants',
  productMedia: 'productMedia',
  slugClaims: 'slugClaims',
  skuClaims: 'skuClaims',
  slugRedirects: 'slugRedirects',
  searchDocuments: 'searchDocuments',
  uploadIntents: 'uploadIntents',
  auditEvents: 'auditEvents',
  outboxEvents: 'outboxEvents',
  inventoryBalances: 'inventoryBalances',
  inventoryReservations: 'inventoryReservations',
  inventoryMovements: 'inventoryMovements',
  carts: 'carts',
  cartItems: 'items',
  orders: 'orders',
  orderItems: 'items',
  orderEvents: 'events',
  orderInternalNotes: 'internalNotes',
  paymentAttempts: 'paymentAttempts',
  payments: 'payments',
  paymentExceptions: 'paymentExceptions',
  providerWebhookEvents: 'providerWebhookEvents',
  deliveryZones: 'deliveryZones',
  financialDocuments: 'financialDocuments',
  userProfiles: 'userProfiles',
  staffMemberships: 'staffMemberships',
} as const;

export type FirestoreCollectionName =
  (typeof firestoreCollections)[keyof typeof firestoreCollections];
